### PR TITLE
Issue17 unified formatting in example code

### LINKED ISSUE #14: Anisotropic solidification filenames break convention
In solidification/anisotropic/phase_field example, dendritic.cpp and dendritic.hpp should be names solidification.cpp and solidification.hpp, respectively, following the same pattern as other example directories (e.g., coarsening/grain_growth/...).

### PR DESCRIPTION
**Pull request by tkphd**
Addresses #17 . Fixes #14.
- Updated formatting, accessors, and templating in MMSP examples. `MMSP::grid::operator()(int i)` is fastest, but does minimal boundary checking. When neighboring points are accessed, `MMSP::grid::operator()(MMSP::vector<int> x)` is strongly preferred. Ad hoc `grid[x][y][z]` should only be used if absolutely necessary to simplify templating and avoid segmentation faults.
- Renamed variables where available to avoid conflicts with MMSP member functions, doing away with explicit namespace declarations (`MMSP::`) within `namespace MMSP{}` block. E.g., a grid object named `grid` requires `MMSP::grid<dim,T> grid(...);` while a more descriptive name, such as `grid<dim,T> oldGrid(...);` does not.
- Where possible, merged explicitly templated updates (`update<2,double>`,`update<3,double>`) into unified functions with `template <int dim, typename T>`. NOTE: This may be a wrong-headed move, esp. in cases where templating over dimension requires an `if.. else if... else` block. A templated function to return the 3-, 9-, or 27-position neighborhood of points would go a long way toward fixing that.
- Added progress bars to examples.

[Review on Reviewable](https://reviewable.io/reviews/mesoscale/mmsp/19)

### CODE REVIEW

**Comment by tkphd** [comment]
Reviewed 56 of 68 files at r1.
Review status: 55 of 66 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by tkphd** [comment]
Sorry for the merge conflict, I pushed a separate commit without thinking. I went ahead and "reviewed" files with only whitespace, commentary, or variable name changes, which do not require any more attention. If you have a chance to review the remaining ~15 files, please do, then assign the pull request back to me (on GitHub) and I'll take care of the merge conflict.

**Comment by tkphd** [comment]
Reviewed 1 of 68 files at r1.
Review status: 36 of 68 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-KB0TXDGU9h1JYNK4D44:-KB0TXDHlDUnTSoN81bq:1064264032) (no related file):*
These examples (with some minor fixes) have been merged into a new branch, https://github.com/mesoscale/mmsp/tree/develop, with some automated build testing. These changes should still be merged to master, since they clean up some cruft and fix some bugs. But, for the purpose of making sure this code compiles and runs, consider cloning the develop branch and opening the "test" directory.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by tkphd** [comment]
Review status: 36 of 68 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-KB0TXDGU9h1JYNK4D44:-KB8XKEqIjXL9UTdrrpz:642588889) (no related file):*
Since #20 has not been merged, if you want the example script to generate PNG output for inspection, you'll need to build mmsp2png on that branch before running the script. Instructions to do that from your local terminal:

1. Create  a local branch for #20 and switch into it
```git checkout -b tkphd-issue18-Visualization_utilities_with_unexpected_results master```
```git branch``` should show a star next to ```tkphd-issue18-Visualization_utilities_with_unexpected_results```.

2. Merge #20 into the new branch
```git pull https://github.com/tkphd/mmsp.git issue18-Visualization_utilities_with_unexpected_results```

3. Build mmsp2png
```cd utility
make mmsp2png
cd ..```

4. If you do not already have a local copy of develop, check it out
```git checkout master
git checkout -b develop master
git pull https://github.com/mesoscale/mmsp.git develop```

5. Run the script
```cd test
./build_examples```

6. If you're satisfied with the results, come back and say so :-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*
<!-- Sent from Reviewable.io -->

**Comment by tkphd** [comment]
Review status: 27 of 100 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-KB0TXDGU9h1JYNK4D44:-KB9v3D1ciFgFADEAj8q:-1782320393) (no related file):*
This is getting messy, which was not my intention. But! Making the shell script to build and run the examples came from the need to test whether the changes in this branch were breaking things, and automating the shell script with clean, informative output on travis-ci required rethinking and revising some of the example codes and back-end. The chickens and eggs are all running wild. 
Anyway, while I was thinking of setting apart a dedicated development branch, none of the changes made here break MMSP functionality, so I think that's an inappropriate approach. In the interests of sticking with the One True Branch workflow, I've chosen to complicate this particular pull request instead of complicating the whole project.
My hope is that inclusion of build_examples.sh will simplify this code review. Feel free to kick said code review back to me if you don't have the time. I'll try to let it sit for at least a week, then review it with fresh eyes. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 13 files at r4.
Review status: 27 of 100 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
What is google doing to help with git?  

---

Reviewed 2 of 13 files at r4, 1 of 5 files at r10.
Review status: 29 of 100 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-:-KBoE1F1UP3VSb7GuBaG:-2072251300)*

**Comment by lucentdan** [comment]
*[a discussion](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-KB0TXDGU9h1JYNK4D44:-KBoLwmxfUVh0Oc-LWbF:164011764) (no related file):*
OK.  I'm looking at the easy ones first.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 5 files at r10.
Review status: 30 of 100 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 5 files at r10.
Review status: 31 of 100 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by tkphd** [comment]
Not sure how you mean, so I'll improvise!
* Google donates to the Software Freedom Conservancy, whence git receives financial and legal assistance. [via](https://developers.google.com/open-source/organizations)
* Of the unit testing frameworks I've seen and directly used, Google's is the most appropriate for MMSP. I've been dabbling with unit testing and code verification -- the gtest submodule is part of the foundations.

---

Review status: 31 of 100 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-:-KBo__nKJ-hF7i4m9trW:-54111014)*

**Comment by lucentdan** [comment]
Reviewed 1 of 29 files at r3, 6 of 35 files at r9, 1 of 30 files at r11.
Review status: 39 of 100 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 5 of 13 files at r4, 1 of 11 files at r8, 2 of 35 files at r9, 1 of 5 files at r10, 1 of 30 files at r11.
Review status: 49 of 100 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/gtest, line 1 \[r12\]](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-KCLb6M3iOth3jGPQfrx:-KCLb6M3iOth3jGPQfry:-1781739338) ([raw file](https://github.com/mesoscale/mmsp/blob/f339cc963630b1c938cb2dc872255306ef9cc02b/test/gtest#L1)):*
Don't know what this does yet, but I assume it is necessary!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 35 files at r9.
Review status: 50 of 100 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by tkphd** [comment]
Review status: 50 of 100 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/gtest, line 1 \[r12\]](https://reviewable.io:443/reviews/mesoscale/mmsp/19#-KCLb6M3iOth3jGPQfrx:-KCLezUrHVBY7yGmC99A:1286620433) ([raw file](https://github.com/mesoscale/mmsp/blob/f339cc963630b1c938cb2dc872255306ef9cc02b/test/gtest#L1)):*
Not strictly necessary, but yes -- this pulls in the Google test source code so we can compile against it without requiring anything of users, esp. those who don't plan to run our unit tests. MMSP.testSuite.{h,c}pp have some details.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 23 files at r12.
Review status: 51 of 100 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 2 of 35 files at r9, 1 of 30 files at r11, 4 of 23 files at r12.
Review status: 58 of 100 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 2 of 13 files at r4, 4 of 35 files at r9.
Review status: 64 of 100 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 68 files at r1, 1 of 25 files at r2.
Review status: 65 of 100 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 35 files at r9.
Review status: 66 of 100 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 35 files at r9.
Review status: 67 of 100 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Comment by lucentdan** [comment]
Reviewed 1 of 26 files at r7.
Review status: 68 of 100 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/19)*

**Pull request merged**
