### PR TITLE
Outline how to contribute.

### PR DESCRIPTION
**Pull request by tkphd**
The proposed changes are intended to explain how to contribute to MMSP using the branching workflow with `master` as the trunk.

Addresses #61.

After code review against `develop`, this code will be merged into `master` and `develop` will be deleted. Thereafter, users who branch from local copies of `develop` may have a confusing time submitting a pull request. There are easy fixes, which can be handled case-by-case or with a blurb in CONTRIBUTING explaining how to set the upstream branch.

---
This change is [Reviewable](https://reviewable.io/reviews/mesoscale/mmsp/62)

### CODE REVIEW

**Comment by lucentdan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CONTRIBUTING.md, line 87 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/62#-L6ImVtW6zf7eEATM218:-L6ImVtW6zf7eEATM219:b-mg4w6w) ([raw file](https://github.com/mesoscale/mmsp/blob/3bdb910d25836d5220f849c5ae5474b0ecb8ccd0/CONTRIBUTING.md#L87)):*
> ```Markdown
> mesoscale/mmsp.*
> 
> 1. Create a fork of [HiPerC][_hiperc] on your personal GitHub account.
> ```

Update links here in line 87? 

---

*[CONTRIBUTING.md, line 102 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/62#-L6ImhNKZZ0G6JZ3i9H6:-L6ImhNKZZ0G6JZ3i9H7:bwhz2ui) ([raw file](https://github.com/mesoscale/mmsp/blob/3bdb910d25836d5220f849c5ae5474b0ecb8ccd0/CONTRIBUTING.md#L102)):*
> ```Markdown
>    - Write your edits, updates, or feature code.
>    - `git status`, `git add -u`, `git status`, and `git commit`,
>      in that order, to carefully add your changes. If something is amiss, follow
> ```

Don't think "carefully" adds anything in line 102... :-)

---

*[CONTRIBUTING.md, line 114 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/62#-L6ImpOQnJCCPZiM9ViT:-L6ImpOQnJCCPZiM9ViU:b72gq7p) ([raw file](https://github.com/mesoscale/mmsp/blob/3bdb910d25836d5220f849c5ae5474b0ecb8ccd0/CONTRIBUTING.md#L114)):*
> ```Markdown
> which we typically conduct using [reviewable][_review].
> 
> ## Happy Coding!
> ```

Nice citation list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/62)*

**Comment by lucentdan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/62)*

**Comment by lucentdan** [comment]
Made two small comments and one required change.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/62#-:-L6In0AXzhBx9PoLK756:b-875oav)*

**Comment by lucentdan** [comment]
Not sure why build is failing?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/62#-:-L6In89sZ4DT5hLCPMDq:b-49k6qa)*

**Comment by tkphd** [comment]
[Once finished reviewing, please un-assign yourself and re-assign me.]

**Comment by tkphd** [comment]
Merged #60 to fix CI errors.

**Comment by lucentdan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mesoscale/mmsp/62)*

**Review by lucentdan — APPROVED** [review]
Nice work.

**Comment by tkphd** [comment]
@lucentdan thanks for your help with this.

**Pull request merged**
