### PR TITLE
Diffusion update

### PR DESCRIPTION
**Pull request by lucentdan**
Updated two of the beginner diffusion problems.  Please have a look.

---
This change is [Reviewable](https://reviewable.io/reviews/mesoscale/mmsp/40)

### CODE REVIEW

**Comment by tkphd** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/beginners_diffusion/1stDiffusion.cpp, line 11 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlOwwodMLri3KelCI41:-KlOwwoecJ4ydZFodsnN:b-v2jrww) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/1stDiffusion.cpp#L11)):*
> ```cpp
>   int nx;
>   int iterations;
>   float dt, diffusionCoefficient, dx;
> ```

- ```double``` is preferable to ```float```, esp. since the grid is storing double-precision data.
- Combine definitions with declarations, giving them one line each. This is C++, not C.
 - ````int nx = 10;```
 - ```int iterations = 100;```
 - ...
 - ```double dt = dx*dx / (4 * diffusionCoefficient);```

Note that this declaration of ```dt``` sweeps the linear stability constant (Co=0.5) under the rug. Not sure whether that's intentional or desirable.

---

*[examples/beginners_diffusion/1stDiffusion.cpp, line 19 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlOz6YRJvdme2z-M-gg:-KlOz6YRJvdme2z-M-gh:bwnqihr) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/1stDiffusion.cpp#L19)):*
> ```cpp
>   dt = dx*dx/diffusionCoefficient/4;
> 	  
>   grid<1,scalar<double> > GRID(1,0,nx);
> ```

I find ```GRID``` and ```GRID2``` non-descript, and prefer ```oldGrid```, and ```newGrid```. Consider renaming.

---

*[examples/beginners_diffusion/1stDiffusion.cpp, line 36 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlOztX1li0PxQqvXqX_:-KlOztX1li0PxQqvXqXa:b-xq17vg) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/1stDiffusion.cpp#L36)):*
> ```cpp
>       }
>       else {
> 	GRID2[x]=(diffusionCoefficient*dt/dx/dx)*(GRID[x-1]-2*GRID[x]+GRID[x+1])+GRID[x];
> ```

Confusing as written. Consider re-ordering after the typical discretization equation, ```GRID2[X] = GRID[x] + dt * diffusionCoefficient * (GRID[x-1] - 2.0*GRID[x] + GRID[x+1]) / (dx * dx);```

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 16 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP-VwJAPMsJW6DqSbl:-KlP-VwJAPMsJW6DqSbm:bpuaq0a) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L16)):*
> ```cpp
> 	diffusionCoefficient = 1.0;
> 	dx = 1.0;
> 	dt = dx*dx/diffusionCoefficient/4;
> ```

Same comment re. doubles and declaration-initialization combination.

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 19 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP-vPA2dJZqseLfVNk:-KlP-vPA2dJZqseLfVNl:b-mimf7r) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L19)):*
> ```cpp
> 
> 	grid<1,scalar<double> > GRID(1,0,nx);
> 	grid<1,scalar<double> > update(1,0,nx);
> ```

```GRID```, ```update``` is a jarring naming scheme. Consider a consistent naming scheme, e.g. ```acorn```, ```oak``` or ```lightning```, ```thunder```. Or ```oldGrid```, ```newGrid```. Torvalds hates class-names in variable-names, but I'm OK with it, as long as it's a part of a descriptive whole.
```


---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 33 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP0oancmyOnYtQRX7_:-KlP0oancmyOnYtQRX7a:b-jyd6v6) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L33)):*
> ```cpp
> 	b1(GRID,0) = Dirichlet;
> 	b0(update,0) = Dirichlet;
> 	b1(update,0) = Dirichlet;
> ```

If somebody compiles this with MPI, these conditions will be applied at the parallel boundaries as well as the domain walls. The long-winded workaround is to test whether the local and global grid boundary coincides:
```
if (x0(GRID)==g0(GRID, 0)) {
    b0(GRID, 0) = Dirichlet;
    b0(update, 0) = Dirichlet;
}
if (x1(GRID)==g1(GRID, 0)) {
    b1(GRID, 0) = Dirichlet;
    b1(update, 0) = Dirichlet;
} 
```

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 39 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP22ITUtr8XDMC6Wst:-KlP22ITUtr8XDMC6Wsu:b287u7r) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L39)):*
> ```cpp
> 	for (int k=0; k<iterations; k++) {
> 		for (int i=0; i<nodes(GRID); i++) {
> 			update(i)=(diffusionCoefficient*dt/dx/dx)*laplacian(GRID,i)+GRID[i];
> ```

Still a confusing way to write this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*
<!-- Sent from Reviewable.io -->

**Comment by tkphd** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/1stDiffusion.cpp, line 11 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlOwwodMLri3KelCI41:-KmCrwjlNpuEfTafLG9G:b-cqz04a) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/1stDiffusion.cpp#L11)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

- ```double``` is preferable to ```float```, esp. since the grid is storing double-precision data.
- Combine definitions with declarations, giving them one line each. This is C++, not C.
 - ````int nx = 10;```
 - ```int iterations = 100;```
 - ...
 - ```double dt = dx*dx / (4 * diffusionCoefficient);```

Note that this declaration of ```dt``` sweeps the linear stability constant (Co=0.5) under the rug. Not sure whether that's intentional or desirable.
</blockquote></details>

Fixed types and initial values.  

I'm not fussed by trying to teach stability in this example.  I put in a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/1stDiffusion.cpp, line 19 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlOz6YRJvdme2z-M-gg:-KmCspfBV9YUS9FgZfyI:bqskj9p) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/1stDiffusion.cpp#L19)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

I find ```GRID``` and ```GRID2``` non-descript, and prefer ```oldGrid```, and ```newGrid```. Consider renaming.
</blockquote></details>

renamed...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/1stDiffusion.cpp, line 36 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlOztX1li0PxQqvXqX_:-KmCt6DvaorSm0D8H3wO:b1td08n) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/1stDiffusion.cpp#L36)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Confusing as written. Consider re-ordering after the typical discretization equation, ```GRID2[X] = GRID[x] + dt * diffusionCoefficient * (GRID[x-1] - 2.0*GRID[x] + GRID[x+1]) / (dx * dx);```
</blockquote></details>

OK - I'm not bothered either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 19 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP-vPA2dJZqseLfVNk:-KmCvTR1riqiR8PgKO0d:b-955bhj) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L19)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

```GRID```, ```update``` is a jarring naming scheme. Consider a consistent naming scheme, e.g. ```acorn```, ```oak``` or ```lightning```, ```thunder```. Or ```oldGrid```, ```newGrid```. Torvalds hates class-names in variable-names, but I'm OK with it, as long as it's a part of a descriptive whole.
</blockquote></details>

How about:

leptocephalus and elver?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 19 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP-vPA2dJZqseLfVNk:-KmCyeom9s5sDXgwFF91:b-88oarn) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L19)):*
<details><summary><i>Previously, lucentdan (Dan Lewis) wrote…</i></summary><blockquote>

How about:

leptocephalus and elver?
</blockquote></details>

Making all suggested changes.. :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
Made changes described above.

**Comment by tkphd** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/beginners_diffusion/1stDiffusion.cpp, line 13 at r2](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KmD8W61MD4QkY2buZ8p:-KmD8W61MD4QkY2buZ8q:b-hfi296) ([raw file](https://github.com/mesoscale/mmsp/blob/79277b4459b1d195231f579ffe7f25021ae8c6ee/examples/beginners_diffusion/1stDiffusion.cpp#L13)):*
> ```cpp
>   double diffusionCoefficient = 1.0, dx = 1.0;
> 
>   // Choice of dt depends on sability criteria.  This
> ```

"stability"

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 10 at r2](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KmDEM6KgeE0VBN581DR:-KmDEM6LpeHSKMahfpS1:b-o5jjq6) ([raw file](https://github.com/mesoscale/mmsp/blob/79277b4459b1d195231f579ffe7f25021ae8c6ee/examples/beginners_diffusion/MMSPDiffusion.cpp#L10)):*
> ```cpp
> 	int nx = 10;
> 	int iterations = 100;
> 	double diffusionCoefficient = 1.0, dx = 1.0;
> ```

For clarity, I would prefer 
```
double diffusionCoefficient = 1.0;
double dx = 1.0;
```
... but that's a stylistic preference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/1stDiffusion.cpp, line 13 at r2](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KmD8W61MD4QkY2buZ8p:-KmDFSTuoOoH_2CeYGom:b-7ql1vq) ([raw file](https://github.com/mesoscale/mmsp/blob/79277b4459b1d195231f579ffe7f25021ae8c6ee/examples/beginners_diffusion/1stDiffusion.cpp#L13)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

"stability"
</blockquote></details>

fixd.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by tkphd** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by tkphd** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 16 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP-VwJAPMsJW6DqSbl:-KmDG0aDZzVkUv_OD40s:b2nhei9) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L16)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Same comment re. doubles and declaration-initialization combination.
</blockquote></details>

FYI

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 33 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP0oancmyOnYtQRX7_:-KmDG26g1Hnii5P3UkKZ:b2nhei9) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L33)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

If somebody compiles this with MPI, these conditions will be applied at the parallel boundaries as well as the domain walls. The long-winded workaround is to test whether the local and global grid boundary coincides:
```
if (x0(GRID)==g0(GRID, 0)) {
    b0(GRID, 0) = Dirichlet;
    b0(update, 0) = Dirichlet;
}
if (x1(GRID)==g1(GRID, 0)) {
    b1(GRID, 0) = Dirichlet;
    b1(update, 0) = Dirichlet;
} 
```
</blockquote></details>

FYI

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 39 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP22ITUtr8XDMC6Wst:-KmDG2xtc_tSw54j0N9a:b2nhei9) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L39)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

Still a confusing way to write this.
</blockquote></details>

FYI

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 10 at r2](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KmDEM6KgeE0VBN581DR:-KmDFx30GKzXcvczbqQr:b2nhei9) ([raw file](https://github.com/mesoscale/mmsp/blob/79277b4459b1d195231f579ffe7f25021ae8c6ee/examples/beginners_diffusion/MMSPDiffusion.cpp#L10)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

For clarity, I would prefer 
```
double diffusionCoefficient = 1.0;
double dx = 1.0;
```
... but that's a stylistic preference.

</blockquote></details>

FYI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
I'm ok with everything.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-:-KmSGjhJMD1tlvBKr2EW:b-m97ih1)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 33 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP0oancmyOnYtQRX7_:-KmSGpiZNNGhzF9UeDLQ:b32w0x) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L33)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

FYI
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 16 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP-VwJAPMsJW6DqSbl:-KmSGqnhP_4fgKBSi9Rr:b32w0x) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L16)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

FYI
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 39 at r1](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KlP22ITUtr8XDMC6Wst:-KmSGsY8u7oY9CePtWHW:b32w0x) ([raw file](https://github.com/mesoscale/mmsp/blob/118e5c78a7683f3d4ad6eef71f29b0238d7faed1/examples/beginners_diffusion/MMSPDiffusion.cpp#L39)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

FYI
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/beginners_diffusion/MMSPDiffusion.cpp, line 10 at r2](https://reviewable.io:443/reviews/mesoscale/mmsp/40#-KmDEM6KgeE0VBN581DR:-KmSGniwzp_5iDU9LOM0:b32w0x) ([raw file](https://github.com/mesoscale/mmsp/blob/79277b4459b1d195231f579ffe7f25021ae8c6ee/examples/beginners_diffusion/MMSPDiffusion.cpp#L10)):*
<details><summary><i>Previously, tkphd (Trevor Keller) wrote…</i></summary><blockquote>

FYI
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Comment by lucentdan** [comment]
All OK with me.

**Comment by tkphd** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/40)*

**Pull request merged**
