### PR TITLE
Convex splitting

### PR DESCRIPTION
**Pull request by tkphd**
Cahn-Hilliard example with advanced numerics (convex splitting, Gauss-Seidel, successive over-relaxation) and parallelism (OpenMP or MPI). Patches to fundamental classes for bugs found in the process.
Supersedes #12, using the feature branch instead of my merged master branch.

[Review on Reviewable](https://reviewable.io/reviews/mesoscale/mmsp/13)

### CODE REVIEW

**Comment by lucentdan** [comment]
Reviewed 2 of 37 files at r1.
Review status: 2 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 3 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 4 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 5 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 6 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 6 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by guyer** [comment]
Review status: 6 of 28 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/MMSP.chapter7.tex, line 19 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7vf2_IbU-c78uYL3yZ:-K7vf2_IbU-c78uYL3y_:2068016875) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/doc/MMSP.chapter7.tex#L19)):*
"contractive" & "expansive"?

---

*[doc/MMSP.chapter7.tex, line 22 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7vfL9Mm3rNZRAbaem_:-K7vfL9Mm3rNZRAbaema:818813701) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/doc/MMSP.chapter7.tex#L22)):*
"antagonisitc"?!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
*[doc/MMSP.chapter7.tex, line 22 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7vfL9Mm3rNZRAbaem_:-K7wZjDpvHmqPmzcOUVL:24805367) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/doc/MMSP.chapter7.tex#L22)):*
Are these here to see if I'm reading?hhhh

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 7 of 28 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 8 of 28 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 2 of 37 files at r1.
Review status: 9 of 28 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 2 of 37 files at r1.
Review status: 10 of 28 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 5 of 37 files at r1.
Review status: 13 of 28 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
*[examples/phase_transitions/solidification/anisotropic/anisotropy.hpp, line 2 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7wgBdi-CRpaEtUQdEe:-K7wgBdj-ErLLr_MLzmn:1710495074) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/examples/phase_transitions/solidification/anisotropic/anisotropy.hpp#L2)):*
This file name breaks your convention of directory and file name being the same.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 2 of 37 files at r1.
Review status: 14 of 28 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 2 of 37 files at r1.
Review status: 15 of 28 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 2 of 37 files at r1.
Review status: 16 of 28 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 2 of 37 files at r1.
Review status: 17 of 28 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
*[examples/phase_transitions/solidification/anisotropic/mmsp2png.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7wiqb_SJh4yXolWfQM:-K7wiqb_SJh4yXolWfQN:15100484) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/examples/phase_transitions/solidification/anisotropic/mmsp2png.cpp#L2)):*
We picked up some errors in the rastering of the image/array in our work.  Did you get this sorted out in this version?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
*[include/MMSP.main.hpp, line 285 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7wj6tHfS2M2SzseT7f:-K7wj6tHfS2M2SzseT7g:-2124020303) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/include/MMSP.main.hpp#L285)):*
What is the rationale behind changing from i to j?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
I don't see a problem with the logic in the MMSP core files.  Looks mostly like != checking and correcting a declaration and renaming i/j.  Are you documenting the commits with why the changes are being made?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-:-K7wjqBl3ku_ArfLlXrc:-1287157138)*

**Comment by lucentdan** [comment]
Reviewed 9 of 37 files at r1.
Review status: 25 of 28 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by lucentdan** [comment]
Reviewed 1 of 37 files at r1.
Review status: 26 of 28 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by tkphd** [comment]
Yes, the MMSP core files are pretty good, so the changes are minor. The i->j change is commit 3e8188b with comment "indexing error in main," NULL pointer check is 4db14e9 "NULL pointer handling for delete operations." Would more verbose commit messages be better? Alternatively, a separate branch with those two commits could be made and issued as a separate pull request. My Git branching workflow is a work in progress.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-:-K7x2bRFKglXvTgKkKQB:-1353796148)*

**Comment by tkphd** [comment]
Review status: 26 of 28 files reviewed at latest revision, 4 unresolved discussions.

---

*[doc/MMSP.chapter7.tex, line 19 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7vf2_IbU-c78uYL3yZ:-K7x5MyN-iOdvJ_BCGFy:-1549139259) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/doc/MMSP.chapter7.tex#L19)):*
Defined in David Eyre's paper and other literature on convex splitting, see "notes" file. I can edit to explain more carefully.

---

*[doc/MMSP.chapter7.tex, line 22 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7vfL9Mm3rNZRAbaem_:-K7x5bt6BzT-v_34P9nP:796233320) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/doc/MMSP.chapter7.tex#L22)):*
Antagonistic input (as to a database) are maliciously intended to break the code. For example, a mesh of UINT with points set to -1 could be antagonistic. In this case, antagonistic initial conditions may have divide-by-zeros or values well outside (-1,1).

---

*[examples/phase_transitions/solidification/anisotropic/anisotropy.hpp, line 2 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7wgBdi-CRpaEtUQdEe:-K7x3aJqx3XBeobs2QZZ:-1195763987) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/examples/phase_transitions/solidification/anisotropic/anisotropy.hpp#L2)):*
Yes and no. The naming is broken, but it's the dendritic.{c,h}pp that break the convention, not anisotropy.hpp. Will rename.

---

*[examples/phase_transitions/solidification/anisotropic/mmsp2png.cpp, line 2 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7wiqb_SJh4yXolWfQM:-K7x6aSZu75yMIir51Sz:10796198) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/examples/phase_transitions/solidification/anisotropic/mmsp2png.cpp#L2)):*
No, that's still incorrect here. Please file a bug report, and I will patch it separately.

---

*[include/MMSP.main.hpp, line 285 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7wj6tHfS2M2SzseT7f:-K7x6mt9LQLyfv7xXOv4:-1808066150) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/include/MMSP.main.hpp#L285)):*
This is an inner loop, within an outer for loop indexed over i. While the C++ standard handles this -- the same name in different scopes compile to different variables -- some compilers issue warnings, and it's poor form.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Comment by oforion** [comment]
*[doc/MMSP.chapter7.tex, line 22 \[r1\]](https://reviewable.io:443/reviews/mesoscale/mmsp/13#-K7vfL9Mm3rNZRAbaem_:-K7x_0DzqwV1_7ABbcRs:-1341958436) ([raw file](https://github.com/mesoscale/mmsp/blob/18640d2bf4bd829ed8994b84300851317d5434e1/doc/MMSP.chapter7.tex#L22)):*
The derivatives of your free energy, the quadratic term in particular, is not correct.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/13)*

**Pull request merged**
