### PR TITLE
Issue18 visualization utilities with unexpected results

### LINKED ISSUE #18: Visualization utilities with unexpected results
- [x] TKmmsp2vti is not a helpful name, but the utility's function (generating VTI files with coloring by grain ID from vector-valued MMSP data) is useful. Either choose a descriptive name or merge into mmsp2vti with a flag to switch modes.
- [x] mmsp2png is a useful idea, but currently there are several implementations depending on the type of data to visualize. Merge the disparate pieces, harmonize rastering with PNG library, and enable command-line switching between visual styles.
- [x] VTK expects column-major data, while MMSP data is row-major. Utilities that raster of nodes(grid) (or, equivalently, nested loops over i, j, k) will therefore produce visualizations rotated 90 degrees. Replace with nested loops over k, j, i.

### LINKED ISSUE #22: mmsp2pvd throws a segmentation fault
The utility for converting MMSP grid data to the ParaView Data format, mmsp2pvd, is outdated, and may no longer fit in the MMSP output framework. At present, the utility throws a segmentation fault when executed using the pattern recommended by the help message, ```mmsp2pvd --output=test.pvd test.dat```, which should simply produce test.pvd and test.vti. This bug is difficult to track down, since the utility internals don't match up with the advertised usage pattern or the best practices for grid access. 

mmsp2pvd takes as command-line input an output filename and a list of input filenames for conversion. The expected output is one PVD file (.pvd) describing some global grid properties (dimensions, spacing) and a list of VTK image files (.vti), plus one VTI file generated from each input file. This framework is useful if each MPI rank writes its local sub-domain to a file of its own, e.g. for the checkpoint at t=100 timesteps, result.0100_r0.dat, result.0100_r1.dat, ..., result.0100_rN.dat. mmsp2pvd should then generate result.0100.pvd, result.0100_r0.vti, result.0100_r1.vti, ..., result.0100_rN.vti.

However, MMSP currently does not have an output mode that matches this pattern. Instead, checkpoints comprise one single file, into which each MPI rank writes its subdomain description and compressed data as a contiguous block. mmsp2pvd could be re-written to export each block as its own vti file, which might be useful for visualizing unreasonably enormous datasets. The alternative utility, mmsp2vti, converts the MMSP checkpoint file into one VTK Image file (VTI).

The incompatibility between MMSP file I/O and the mmsp2pvd utility is a bit of a conundrum. It is not unreasonable to believe that some users would like to have the option to write one file-per-rank and visualize just one block at a time, or the whole, at will. Until such a need arises, however, the best course is to remove mmsp2pvd from the repository. If extremely large grid support becomes necessary, the appropriate checkpoint input and output functions will be written, then mmsp2pvd may be resurrected.

### PR DESCRIPTION
**Pull request by tkphd**
- Folded TKmmsp2vti functionality into mmsp2vti, with command line flag to switch modes (--mag is default, --max flattens data by maximal index) for vector- and sparse-valued data.
- Created monolithic mmsp2png, with command line flags to switch modes (--mag, --field, --exclude, --contour, --zoom, --invert) between visual styles and to select specific fields from vector- and sparse-valued data for inspection. Folded mmspslicer functionality in with command line flag (--slice). Replaced DevIL with libpng to ease installation.
- Fixed rastering in VTI and PNG converters.
- Ported mmsp2vti changes into mmsp2pvd.

~~The new or renovated utilities have been tested with several vector-valued 2-D grids. Testing against scalar and sparse data and pan-dimensional grids needs to be done.~~
```mmsp2png```, ```mmsp2vti```, and ```mmsp2pvd``` have been tested on each of the examples (except Poisson, see #23) and produce consistent visual representations of the data as of 6a65ed3.

Closes #18. Closes #22.

[Review on Reviewable](https://reviewable.io/reviews/mesoscale/mmsp/20)

### CODE REVIEW

**Comment by tkphd** [comment]
Reviewed 2 of 3 files at r1, 2 of 4 files at r3, 2 of 4 files at r5, 3 of 6 files at r6, 3 of 3 files at r7.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20)*

**Comment by tkphd** [comment]
mmsp2pvd is severely outdated and needs considerable work, but has not been changed at all. The rest look good to me.

---

Review status: 11 of 12 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-:-KB9fXutOzqzEB32IOki:1808381381)*

**Comment by tkphd** [comment]
Reviewed 1 of 6 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20)*

**Comment by lucentdan** [comment]
Reviewed 8 of 12 files at r8.
Review status: 15 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20)*

**Comment by lucentdan** [comment]
Review status: 15 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[utility/mmsp2xyz.cpp, line 27 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCLZumT9Xp-bJGtj-Jd:-KCLZumT9Xp-bJGtj-Je:-824700151) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L27)):*
I see the pattern here.  Nothing looks out of place.

---

*[utility/mmsp2xyz.cpp, line 35 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCL_-8LjvvNdXJj_3Ml:-KCL_-8LjvvNdXJj_3Mm:-490100116) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L35)):*
Nice.

---

*[utility/mmsp2xyz.cpp, line 49 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCL_0ZPnhJzMZUWqNRS:-KCL_0ZPnhJzMZUWqNRT:-1789783500) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L49)):*
OK on this one too.

---

*[utility/mmsp2xyz.cpp, line 69 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCL_BSpw19dygiUMDWC:-KCL_BSpw19dygiUMDWD:983750067) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L69)):*
"contol"??  I don't see "contol" in the help diagnostic.  So I'm a bit confused.

---

*[utility/mmsp2xyz.cpp, line 170 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCL_mKAFLl1QOxrDmeg:-KCL_mKAFLl1QOxrDmeh:-2003046499) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L170)):*
Extra line for some reason?

---

*[utility/mmsp2xyz.cpp, line 220 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCLa-0ie0WDvzHWCfJK:-KCLa-0ie0WDvzHWCfJL:1508146864) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L220)):*
Are we keeping rectilinear dr = 1 for the forseeable future?

---

*[utility/mmsp2xyz.cpp, line 978 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCLaAvl0Psptlb84Qnv:-KCLaAvl0Psptlb84Qnw:680167109) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L978)):*
I'm trusting all the conversions are OK.  I can test them a bit later, but clear them for now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20)*

**Comment by lucentdan** [comment]
Reviewed 1 of 2 files at r9.
Review status: 16 of 21 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20)*

**Comment by lucentdan** [comment]
I will work on this in the next few days.  I'm still getting used to Reviewable.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-:-KCLccfjGZYIfG-9igGi:2056944387)*

**Comment by tkphd** [comment]
Review status: 16 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[utility/mmsp2xyz.cpp, line 170 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCL_mKAFLl1QOxrDmeg:-KCLe5BGyxSyachAUtpz:-1337770436) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L170)):*
Yes, dividing the fundamental types (int, float) from MMSP container classes (scalar, vector, double).

---

*[utility/mmsp2xyz.cpp, line 220 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCLa-0ie0WDvzHWCfJK:-KCLeK_hRTRX9_f59Jkv:2059834825) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L220)):*
Yes, rectilinear is sticking around. dr=1 is arbitrary; {1,1,1} is just a default.

---

*[utility/mmsp2xyz.cpp, line 978 \[r9\]](https://reviewable.io:443/reviews/mesoscale/mmsp/20#-KCLaAvl0Psptlb84Qnv:-KCLecfZUGw-abWHwxts:-1619476151) ([raw file](https://github.com/mesoscale/mmsp/blob/d410fe99d750a58b7c428bcdcb8cd54036af1495/utility/mmsp2xyz.cpp#L978)):*
OK. Running the test suite (from the other pull request) will exercise these conversions for mmsp2{vti,pvd,png}.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mesoscale/mmsp/20)*

**Comment by tkphd** [comment]
Reviewed 12 of 12 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mesoscale/mmsp/20)*

**Pull request merged**
